name: Run Allpix Squared

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_allpix:
    runs-on: self-hosted  # Keep using the default runner location
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Allpix Squared Simulation
        run: |
          chmod +x scripts/run_allpix.sh
          ./scripts/run_allpix.sh

      - name: Move Output Files to Project Directory
        run: |
          mv ~/Software/actions-runner/_work/particle-simulation/particle-simulation/output/* ~/particle-simulation/output/
