name: Run Allpix Squared

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_allpix:
    runs-on: self-hosted  # Use your local self-hosted runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Allpix Squared Simulation
        run: |
          chmod +x scripts/run_allpix.sh
          ./scripts/run_allpix.sh
