name: Run Allpix Squared

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_allpix:
    runs-on: self-hosted  # Use your local self-hosted runner
    steps:
      - name: Checkout repository into project directory
        uses: actions/checkout@v4
        with:
          path: /home/pko/particle-simulation  # Replace with your actual project path


      - name: Run Allpix Squared Simulation
        run: |
          chmod +x scripts/run_allpix.sh
          ./scripts/run_allpix.sh
